### ISSUE TITLE
Specifying a list of servers using `-s` is ignored

### ISSUE THREAD

**Issue by excelero-joe** [Excelero/nvmesh-shell#12]
While trying to limit the target servers for a new volume using the `-s` flag, it has been observed the CLI or API is ignoring the selection and making its own choices.

**Comment by excelero-joe** [comment]
To add further color, I believe this to be the CLI based on the API call found in the log and the lack of server names contained in the `limitByNodes` key.

`2019-04-12 11:33:49,207 - DEBUG    - API payload: {'edit': [], 'create': [{'capacity': 107374182400, 'name': 'joe', 'serverClasses': [], 'RAIDLevel': 'Striped & Mirrored RAID-10', 'stripeSize': 32, 'limitByDisks': [], 'limitByNodes': [], 'stripeWidth': 2, 'numberOfMirrors': 1}], 'remove': []}`

**Comment by excelero-andreas** [comment]
That's a bug - will fix it and also add input validation to make sure valid hostnames are provided.

**Comment by excelero-andreas** [comment]
Fix provided in v1.3.50
