### ISSUE TITLE
Target NIC show and delete

### ISSUE THREAD

**Issue by excelero-joe** [Excelero/nvmesh-shell#13]
Request an enhancement to the shell to support listing the NIC ID of NVMesh-targets and enable the API calls to remove them as required in the event of failure and replacement.  As clients do not register their NIC ID, this feature is not required for those systems acting solely as clients.

**Comment by excelero-andreas** [comment]
Done.
Available in the new 53 build.
`show target -d` will show the NIC details and with `delete nic` you will be able to delete missing NIC's
