### ISSUE TITLE
Provide warning and ask for verification when performing invasive and possible destructive activities.

### ISSUE THREAD

**Issue by excelero-andreas** [Excelero/nvmesh-shell#6]
Provide a warning and verification message for:
- Delete Volume
- Format Drive
- Detach Volume
- Stop target, management and/or client service

**Comment by excelero-andreas** [comment]
Joe, can you please give a one-liner for each of these activities?

**Comment by excelero-joe** [comment]
**- Delete Volume:**  This operation will DESTROY ALL DATA on this volume and is IRREVERSIBLE.
**- Format Drive:**  This operation will DESTROY ALL DATA on this drive and is IRREVERSIBLE.
**- Force-Detach Volume:**  This operation will immediately HALT ALL I/O and will impact any running applications expecting it to be available.  It is recommended that all applications and/or file systems using this volume be stopped/un-mounted prior to issuing the command.
**- Stop nvmeshclient service:**  This operation will HALT ALL I/O TO ALL VOLUMES in use by THIS CLIENT.  It is recommended that all applications and/or file systems supported by NVMesh volumes on this client be stopped/un-mounted prior to issuing the command.
**- Stop nvmeshtarget service:**  This operation will make any UNPROTECTED VOLUMES supported by drives in this target IMMEDIATELY UNAVAILABLE.  Any PROTECTED VOLUMES will become IMMEDIATELY DEGRADED until services are restarted or volumes are rebuilt to alternate drives in another target.
**- Stop nvmeshmgr service:**  This operation will halt the running instance of NVMesh Management on this server.  If Management is deployed as a stand-alone instance, or this is the last running HA instance, further changes to NVMesh cluster volumes, clients, and targets will be unavailable until Management is restarted on at least one node.

**Comment by excelero-andreas** [comment]
Thx - moving it into my queue
